# Generated by Django 4.2.5 on 2024-01-22 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SwiperContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='swiper_images/')),
                ('online_class_url', models.URLField()),
                ('offline_class_url', models.URLField()),
            ],
        ),
    ]
