# Generated by Django 4.2.5 on 2024-01-22 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winnerapp', '0003_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio_content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='swiper_images/')),
                ('heading', models.CharField(max_length=255)),
                ('paragraph', models.TextField()),
            ],
        ),
    ]
