# Generated by Django 4.2.5 on 2024-01-22 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winnerapp', '0004_portfolio_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to='blog_images/')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
