# Generated by Django 4.2.5 on 2024-01-27 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winnerapp', '0008_course_description_course_heading'),
    ]

    operations = [
        migrations.CreateModel(
            name='Online_admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=255)),
                ('lname', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phonno', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=255)),
                ('qualification', models.CharField(max_length=255)),
                ('course', models.CharField(max_length=255)),
                ('dob', models.CharField(max_length=255)),
            ],
        ),
    ]
