# Generated by Django 4.2.5 on 2024-01-27 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winnerapp', '0009_online_admission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_student_corner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='team_images/')),
            ],
        ),
    ]
