# Generated by Django 4.2.5 on 2024-01-29 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winnerapp', '0010_add_student_corner'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='qualification',
            field=models.CharField(default='', max_length=255),
        ),
    ]
