# Generated by Django 4.2.5 on 2024-01-29 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('winnerapp', '0011_team_qualification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio_content',
            name='image',
        ),
    ]
