# Generated by Django 4.2.5 on 2024-01-29 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winnerapp', '0012_remove_portfolio_content_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio_content',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
