# Generated by Django 4.2.5 on 2024-01-30 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winnerapp', '0013_portfolio_content_video_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='careers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('resume', models.FileField(default='default_pdf.pdf', upload_to='resumes')),
            ],
        ),
    ]
