# Generated by Django 4.2.5 on 2024-01-30 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winnerapp', '0014_careers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sylabbus_pdf', models.FileField(default='default_pdf.pdf', upload_to='resumes')),
            ],
        ),
    ]
