# Generated by Django 4.2.5 on 2024-02-01 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winnerapp', '0015_syllabus'),
    ]

    operations = [
        migrations.AddField(
            model_name='careers',
            name='dob',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='careers',
            name='qualafication',
            field=models.CharField(default='', max_length=255),
        ),
    ]
