# Generated by Django 4.2.5 on 2024-02-01 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('winnerapp', '0016_careers_dob_careers_qualafication'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.RemoveField(
            model_name='swipercontent',
            name='online_class_url',
        ),
    ]
