# Generated by Django 4.2.5 on 2024-02-01 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('winnerapp', '0017_delete_course_remove_swipercontent_online_class_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='swipercontent',
            name='offline_class_url',
        ),
    ]
